name: ESBOÇO
favicon: null
layout_spectrum: 0.9662711943965405
typography_spectrum: 0.7797257325146347
title: ESBOÇO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#182313'
    - '#dfedf8'
    - '#006ea9'
    - '#86a4c6'
    - '#ff4d4d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
